name: mini_ginger_web
description: Mini Standalone Flutter Web App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.7+7

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  amplitude_flutter: ^3.9.0
  care_dart_sdk:
    git:
      url: git@github.com:HeadspaceMeditation/care_dart_sdk.git
      ref: develop
  console: ^4.1.0
  dart_openai: ^1.9.91
  excel: ^2.1.0
  googleapis_auth: ^1.0.0
  qr_flutter: ^4.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  jwt_decoder: ^2.0.1
  http: 0.13.6

dev_dependencies:
  alchemist: ^0.6.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  flutter_lints: ^2.0.0
  mocktail: ^1.0.0

dependency_overrides:
  async: 2.11.0
  collection: 1.17.1
  intl: ^0.18.1
  meta: 1.9.1
  universal_html: 2.2.4

flutter_icons:
  image_path_android: "assets/launcher/ginger_android_icon.png"
  image_path_ios: "assets/launcher/ginger_ios_icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/cfg/
  fonts:
    - family: ApercuPro
      fonts:
        - asset: assets/fonts/apercu_pro_regular.otf
        - asset: assets/fonts/apercu_pro_bold.otf
          weight: 700
    - family: ApercuMono
      fonts:
        - asset: assets/fonts/apercu_mono.otf

    - family: SfProText
      fonts:
        - asset: assets/fonts/sfprotextregular.otf

executables:
  localization: bin/localization/localization
